- name: Install Nginx server
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: startt service
    ansible.builtin.service:
      name: nginx
      state: started
  
- name: Install Git server
  hosts: web
  become: yes
  tasks:
  - name: install git
    ansible.builtin.package:
      name: git
      state: present
  