- name: variables
  hosts: local
  connection: local
  vars:
    COURSE:    "Devops"
    DURATION: "1hr"
    TRAINEE: "Kavya"
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "course is {{COURSE}}, Duration is {{DURATION}}, Trainee is {{TRAINEE}}"