- name: print variables
  hosts: local
  connection: local
  vars:
   Name: "kavya"
   age: "21"
  tasks:
  - name: print the mesaage
    ansible.builtin.debug:
      msg: I am  {{ Name }} and my age is {{ age }}