- name: print vars
  hosts: local
  vars:
    Name: "kavya"
    Age: "21"
  tasks:
  - name: print the vars
    vars:
      Name: "Divya"
    ansible.builtin.debug:
      msg: "my nane is {{ Name }}"
      
  - name: print the vars
    ansible.builtin.debug:
      msg: "my name is {{   Name }},and my Age is {{ Age}}"