- name: variables
  hosts: local
  connection: local
  vars:
    COURSE:    "Devops"
    DURATION: "1hr"
    TRAINEE: "Kavya"

    
  tasks:
  - name: "print the variables"
    vars:
      COURSE: ansible
    ansible.buitlin.debug:
      msg: "Course is {{COURSE}}, duration is {{DURATION}}, Trainmee is {{TRAINEE}}"
    
  - name: "print the varaibles"
    ansible.buitlin.debug:
       msg: "Course is {{COURSE}}, duration is {{DURATION}}, Trainmee is {{TRAINEE}}"

    