- name: "prefer"
  hosts: local
  connection: local
  vars:
    GREET: "PLay"
  vars_files:
  - vars.yaml
  vars_prompt:
  - name: GREET
    prompt: enter the value
    private: false
  tasks:
  - name: "print vars"
    vars:
      GREET: "TASK"
    ansible.builtin.debug:
       msg: "Hello from {{GREET}}"
  
  