- name: install aws and ec2 records
  hosts: local
  connection: local
  vars:
    subent_id:
    sg_id:
    instance_type: t3.micro
    ami_id:
    instances:
    - mysql
    - frontend
  tasks:
  - name: install aws ec2 instances
    amazon.aws.ec2.instance:
    name : "{{ item }}"
    subnet_id: "{{ subent_id }}"
    ami_id: "{{ ami_id}}"
    sg_id: "{{ sg_id}}"
    instance_type: "{{ instance_type}}"
  loop: "{{ instances }}"000000000000000................0.