- name: create ec2 and r53 key
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-081aa136223dd7479
    security_group_id: sg-06e21e4e0e03360b0
    ami_id: ami-09c813fb71547fc4f
    instance_id: t3.micro

    instances:
    - mysql:
    - backend:
    - frontend:
  tasks:
  - name: create ec2  instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      sg_id: "{{ security_group_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
